import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import App from "@/App.tsx";
import "./index.css";
import Auth from "@/Auth.tsx";
import ListOfCompanyAndJobs from "@/ListOfCompanyAndjobs.tsx";
import Navbar from "@/Navbar.tsx";
import JobApplyPage from "@/JobApplyPage.tsx";
import CompanyPofilePage from "@/CompanyProfilePage.tsx";
import CandidateFillUpPage from "@/CandidateFillUpPage.tsx";
import TalentFilterPage from "@/TalentFilterPage.tsx";
// import Home from "@/Home.tsx";
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsxs(BrowserRouter, { children: [_jsx(Navbar, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(App, {}) }), _jsx(Route, { path: "/login", element: _jsx(Auth, {}) }), _jsx(Route, { path: "/list", element: _jsx(ListOfCompanyAndJobs, {}) }), _jsx(Route, { path: "/job-apply", element: _jsx(JobApplyPage, {}) }), _jsx(Route, { path: "/company-page", element: _jsx(CompanyPofilePage, {}) }), _jsx(Route, { path: "/candidate-fillup", element: _jsx(CandidateFillUpPage, {}) }), _jsx(Route, { path: "/find", element: _jsx(TalentFilterPage, {}) }), _jsx(Route, { path: "*", element: _jsx(App, {}) })] }), " "] }) }));
